### ISSUE TITLE
Version 0.4.5 cannot be installed via pip

### ISSUE THREAD

**Issue by matt-caz** [smerckel/dbdreader#2]
Hi,

The source tarball for 0.4.5 (https://files.pythonhosted.org/packages/2c/8f/61f0c8a1b450d6d0d1204406e2fd616dca32877e1ef6a355b1f831d309c2/dbdreader-0.4.5.linux-x86_64.tar.gz) appears to have a malformed directory structure, as a result pip/PyPi does not recognise it and 0.4.5 is not available for installation.

```
$ pip install dbdreader==0.4.5
Collecting dbdreader==0.4.5
  ERROR: Could not find a version that satisfies the requirement dbdreader==0.4.5 (from versions: 0.4.5.linux-x86_64, 0.3.6, 0.3.7, 0.3.8, 0.3.10, 0.4.1, 0.4.3)
ERROR: No matching distribution found for dbdreader==0.4.5
```

For comparison, 0.4.3 (https://files.pythonhosted.org/packages/37/82/4568502632d5fa100bc91c0c98ed939002844a7de20d331b70ec0a34f179/dbdreader-0.4.3.tar.gz) is compliant and installs fine.

**Comment by smerckel** [comment]
Hi Matt-caz,

Thank you for pointing this out. Version 0.4.5 has been removed and replaced by 0.4.6, which should install, and has a small bug fix too.
